version: "3.1"
services:

 wordpress:
  image: wordpress:php7.4-fpm-alpine
  container_name: wordpress
  ports:
    - 9000:9000
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: user
    WORDPRESS_DB_PASSWORD: password
    WORDPRESS_DB_NAME: mysqldb
    WORDPRESS_REDIS_HOST: redis
  volumes:
    - wordpress:/var/www/html
  depends_on:
    - db
  networks:
    - app-network

 web:
  image: nginx
  container_name: nginx
  volumes:
    - wordpress:/var/www/html
    - ./templates:/etc/nginx/conf.d
  ports:
    - 8080:80
  depends_on:
      - wordpress
  networks:
    - app-network

 redis:
    image: redis
    container_name: redis
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    networks:
      - app-network

 db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes: 
      - db:/var/lib/mysql
    networks:
      - app-network

volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge 