version: "3.1"
services:

 wordpress:
  image: wordpress:php7.4-fpm-alpine
  container_name: wordpress
  ports:
    - 9000:9000
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: user
    WORDPRESS_DB_PASSWORD: password
    WORDPRESS_DB_NAME: mysqldb
    WORDPRESS_REDIS_HOST: redis
  volumes:
    - wordpress:/var/www/html
  depends_on:
    - db
  networks:
    - app-network
  deploy:
    mode: replicated
    replicas: 2 

 web:
  image: nginx
  container_name: nginx
  volumes:
    - wordpress:/var/www/html
    - ./templates:/etc/nginx/conf.d
  ports:
    - 8080:80
  depends_on:
      - wordpress
  networks:
    - app-network
  deploy:
    mode: replicated
    replicas: 2

 redis:
    image: redis
    container_name: redis
    depends_on:
      - wordpress
    networks:
      - app-network

 db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: toor
    volumes: 
      - db:/var/lib/mysql
    networks:
      - app-network
 
 adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports: 
      - 8090:8080
    depends_on:
      - db
    networks:
      - app-network  

 traefik:
    image: traefik:2.8
    container_name: traefik
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app-network

volumes:
  wordpress:
  db:

networks:
  app-network:
    driver: bridge 