version: "3.1"
services:

 wordpress:
  image: wordpress:php7.4-fpm-alpine
  container_name: wordpress
  ports:
    - 9000:9000
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: user
    WORDPRESS_DB_PASSWORD: password
    WORDPRESS_DB_NAME: mysqldb
    WORDPRESS_REDIS_HOST: redis
  volumes:
    - wordpress:/var/www/html
  depends_on:
    - db
  networks:
    - internal
  deploy:
    mode: replicated
    replicas: 2 

 web:
  image: nginx
  container_name: nginx
  volumes:
    - wordpress:/var/www/html
    - ./templates:/etc/nginx/conf.d
  ports:
    - 8080:80
  depends_on:
      - wordpress
  networks:
    - internal
    - proxy
  deploy:
    mode: replicated
    replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
             
 redis:
    image: redis
    container_name: redis
    depends_on:
      - wordpress
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"

 db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: toor
    volumes: 
      - db:/var/lib/mysql
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"
 
 adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports: 
      - 8090:8080
    depends_on:
      - db
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"  

 traefik:
    image: traefik:2.8
    container_name: traefik
    ports:
      - 80:80
    volumes:
      - ./traefik/traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - web
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1    

volumes:
  wordpress:
  db:

networks:
  proxy:
    external: true
    name: proxy
  internal:
    external: false
    name: internal