version: '3.1'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    command: --docker --docker.domain=localhost
    ports:
      - 80:80
    networks:
      - proxy
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./tls.yaml:/tls.yaml

networks:
  proxy:
    external: true