# http:
#     routers:
#         http_router:
#             rule: "Host(`docker.loc`)"
#             service: allbackend
       
#     services:
#         allbackend:
#             loadBalancer:
#                 servers:
#                     - url: "http://myserver1/"
#                     - url: "http://myserver2/"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: ./ssl/docker.loc.crt
        keyFile: ./ssl/docker.loc.key

  certificates:
      certFile: ./ssl/docker.loc.crt
      keyFile: /ssl/docker.loc.key