http:
    routers:
        http_router:
            rule: "Host(`docker.loc`)"
            service: wordpress

    services:
        wordpress:
            loadBalancer:
                servers:
                    - url: "http://myserver1/"
                    - url: "http://myserver2/"

