http:
    routers:
        http_router:
            rule: "Host(`traefik.docker.loc`)"
            service: allbackend

    services:
        allbackend:
            loadBalancer:
                servers:
                    - url: "https://myserver1/"
                    - url: "https://myserver2/"
