# Static configuration
entryPoints:
    unsecure:
        address: :80
    secure:
        address: :443
        
providers:
    file:
      filename: tls.yaml
      
    docker:
      endpoint: unix:///var/run/docker.sock
      watch: true
      exposedByDefault: true

