# Static configuration
entryPoints:
    unsecure:
        address: :80
    secure:
        address: :443
        http:
          tls:
            certResolver: 
        
providers:
    file:
      filename: tls.yaml

